### ISSUE TITLE
APNG Animation Playing Too Fast

### ISSUE THREAD

**Issue by alexander-steel** [onevcat/APNGKit#139]
Hi. I have an issue where the APNG animation plays at an extremely fast speed when I load it with a certain piece of code. Is this a bug?

"The application starts by displaying a splash screen. After the splash screen completes, the main ViewController is loaded. The APNG images are set up within the viewDidLoad method of the main ViewController."

https://github.com/onevcat/APNGKit/assets/43738569/e7d48f51-e0a0-4104-bb0a-1fa7c4c16591

```swift

let apngImage = try! APNGImage(named: defaultImageName)
        imageView.autoStartAnimationWhenSetImage = false
        setImage(image: apngImage)
        imageView.startAnimating()
    }

    private func setImage(image: APNGImage) {
        imageView.image = image
        setFrameSize(image: image)
    }

    private func setFrameSize(image: APNGImage) {
        let deviceWidth = UIScreen.main.bounds.width
        let frameHeight = deviceWidth * image.size.height / image.size.width
        frame.size = CGSize(width: deviceWidth, height: frameHeight)
    }

```

**Comment by onevcat** [comment]
@alexander-steel Does the same thing happen in the `viewWillAppear:`? And if possible, can you give me a link or post the used image here? I can check if it is the issue in the image itself.

**Comment by devflow** [comment]
Same issue on iOS 17. but 16 works normally.

**Comment by devflow** [comment]
@onevcat 

I've committed a few lines to my repository to reproduce the bug (Master branch) Please check it!, thanks!

[https://github.com/devflow/APNGKit](https://github.com/devflow/APNGKit)

**Comment by onevcat** [comment]
Umm, seems it is an issue that the first `.applicationDidBecomeActive` notification comes earlier for the app startup than iOS 16, and an edge case happens if there is already an instance of `APNGImage` which receives a wrong timestamp.

Fixed in #140

**Comment by onevcat** [comment]
Fixed and released as 2.2.4.

**Comment by devflow** [comment]
it seems like still having issue. at my forked repo with apngkit 2.2.4. (iOS 17, Simulator)

**Comment by devflow** [comment]
> it seems like still having issue. at my forked repo with apngkit 2.2.4. (iOS 17, Simulator)

Ok, it's only happening when launch an app with XCode. other normal app launch behavior likes SB or Spotlight works as well. it not important issue.

Thank you.

**Comment by onevcat** [comment]
A stupid error. I will fix again soon.

**Comment by onevcat** [comment]
Ref: #141

**Comment by onevcat** [comment]
@devflow Done in 2.2.5. Any luck to check it again?

**Comment by devflow** [comment]
@onevcat yes, 2.2.5 works as well!! at both DEMO and the private project. 💯
